site_name: {{ cookiecutter.project_name }}
site_description: {{ cookiecutter.description }}
site_author: {{ cookiecutter.organization_name }}
site_url: https://{{ cookiecutter.organization_name | lower | replace(' ', '') }}.github.io/{{ cookiecutter.repo_name }}
repo_url: https://github.com/{{ cookiecutter.organization_name | lower | replace(' ', '') }}/{{ cookiecutter.repo_name }}
repo_name: {{ cookiecutter.repo_name }}
edit_uri: edit/main/docs/content/
docs_dir: docs/content

# Watch additional directories for changes
watch:
  - docs/content
  - {{ cookiecutter.module_name }}

theme:
  name: material
  language: en
  custom_dir: docs/content/overrides
  palette:
    scheme: default
    primary: indigo
  font:
    text: Roboto
  logo: images/logo/nhs-blue-on-white.jpg
  favicon: images/favicon/favicon.ico
  features:
    - search.share
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.path
    - navigation.top
    - toc.integrate
  icon:
    admonition:
      <type>: material/alert

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            members_order: source
            show_source: true
            show_bases: true
            extra:
              show_inheritance: true

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Usage: usage.md
  - Contributing: contributing.md
  - API Reference:
    - api_reference/index.md

extra_css:
  - stylesheets/nhs_style.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/{{ cookiecutter.organization_name | lower | replace(' ', '') }}/{{ cookiecutter.repo_name }}{% if cookiecutter.team_email %}
    - icon: fontawesome/solid/envelope
      link: mailto:{{ cookiecutter.team_email }}{% endif %}
  generator: false

copyright: Copyright &copy; {% now 'utc', '%Y' %} Crown Copyright ({{ cookiecutter.organization_name }})

markdown_extensions:
  - tables
  - attr_list
  - pymdownx.emoji
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.mark
  - md_in_html
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.tilde

extra_javascript:
  - javascripts/mermaid.mjs
