# Test configurations for cookiecutter template
# Each configuration tests different combinations of options
# All values must match options in cookiecutter.json

minimal:
  config_description: "Bare minimum setup - no extras"
  project_name: "minimal_project"
  author_name: "Test Author"
  author_email: "test@example.com"
  organization_name: "NHS England"
  team_name: "Test Team"
  team_email: "test.team@nhs.net"
  description: "Minimal test project"
  python_version_number: "3.10"
  git_hosting_platform: "github"
  repository_url: "https://github.com/nhsengland/minimal_project"
  environment_manager: "virtualenv"
  testing_framework: "pytest"
  linting_and_formatting: "ruff"
  open_source_license: "No license file"
  docs: "none"
  include_code_scaffold: "No"

full_featured:
  config_description: "All features enabled"
  project_name: "full_featured_project"
  author_name: "Test Author"
  author_email: "test@example.com"
  organization_name: "NHS England"
  team_name: "Test Team"
  team_email: "test.team@nhs.net"
  description: "Full featured test project"
  python_version_number: "3.10"
  git_hosting_platform: "github"
  repository_url: "https://github.com/nhsengland/full_featured_project"
  environment_manager: "uv"
  testing_framework: "pytest"
  linting_and_formatting: "ruff"
  open_source_license: "MIT"
  docs: "mkdocs"
  include_code_scaffold: "Yes"

conda_env:
  config_description: "Conda environment setup"
  project_name: "conda_project"
  author_name: "Test Author"
  author_email: "test@example.com"
  organization_name: "NHS England"
  team_name: "Test Team"
  team_email: "test.team@nhs.net"
  description: "Conda environment test project"
  python_version_number: "3.10"
  git_hosting_platform: "gitlab"
  repository_url: "https://gitlab.com/nhsengland/conda_project"
  environment_manager: "conda"
  testing_framework: "pytest"
  linting_and_formatting: "ruff"
  open_source_license: "Apache-2.0"
  docs: "mkdocs"
  include_code_scaffold: "Yes"

poetry_project:
  config_description: "Poetry environment setup"
  project_name: "poetry_project"
  author_name: "Test Author"
  author_email: "test@example.com"
  organization_name: "NHS England"
  team_name: "Test Team"
  team_email: "test.team@nhs.net"
  description: "Poetry environment test project"
  python_version_number: "3.10"
  git_hosting_platform: "github"
  repository_url: "https://github.com/nhsengland/poetry_project"
  environment_manager: "poetry"
  testing_framework: "pytest"
  linting_and_formatting: "flake8+black+isort"
  open_source_license: "MIT"
  docs: "mkdocs"
  include_code_scaffold: "Yes"

pixi_project:
  config_description: "Pixi environment setup"
  project_name: "pixi_project"
  author_name: "Test Author"
  author_email: "test@example.com"
  organization_name: "NHS England"
  team_name: "Test Team"
  team_email: "test.team@nhs.net"
  description: "Pixi environment test project"
  python_version_number: "3.10"
  git_hosting_platform: "azure_devops"
  repository_url: "https://dev.azure.com/nhsengland/pixi_project"
  environment_manager: "pixi"
  testing_framework: "pytest"
  linting_and_formatting: "ruff"
  open_source_license: "MIT"
  docs: "none"
  include_code_scaffold: "Yes"

pipenv_project:
  config_description: "Pipenv environment setup"
  project_name: "pipenv_project"
  author_name: "Test Author"
  author_email: "test@example.com"
  organization_name: "NHS England"
  team_name: "Test Team"
  team_email: "test.team@nhs.net"
  description: "Pipenv environment test project"
  python_version_number: "3.10"
  git_hosting_platform: "github"
  repository_url: "https://github.com/nhsengland/pipenv_project"
  environment_manager: "pipenv"
  testing_framework: "pytest"
  linting_and_formatting: "ruff"
  open_source_license: "MIT"
  docs: "mkdocs"
  include_code_scaffold: "Yes"

no_env_manager:
  config_description: "No environment manager"
  project_name: "no_env_manager_project"
  author_name: "Test Author"
  author_email: "test@example.com"
  organization_name: "NHS England"
  team_name: "Test Team"
  team_email: "test.team@nhs.net"
  description: "No environment manager test project"
  python_version_number: "3.10"
  git_hosting_platform: "other"
  repository_url: "https://example.com/nhsengland/no_env_manager_project"
  environment_manager: "none"
  testing_framework: "pytest"
  linting_and_formatting: "ruff"
  open_source_license: "No license file"
  docs: "none"
  include_code_scaffold: "No"

old_school_linting:
  config_description: "Old school flake8+black+isort setup"
  project_name: "old_school_project"
  author_name: "Test Author"
  author_email: "test@example.com"
  organization_name: "NHS England"
  team_name: "Test Team"
  team_email: "test.team@nhs.net"
  description: "Old school linting test project"
  python_version_number: "3.10"
  git_hosting_platform: "github"
  repository_url: "https://github.com/nhsengland/old_school_project"
  environment_manager: "virtualenv"
  testing_framework: "pytest"
  linting_and_formatting: "flake8+black+isort"
  open_source_license: "MIT"
  docs: "mkdocs"
  include_code_scaffold: "Yes"

docs_no_scaffold:
  config_description: "Docs without code scaffold"
  project_name: "docs_no_scaffold_project"
  author_name: "Test Author"
  author_email: "test@example.com"
  organization_name: "NHS England"
  team_name: "Test Team"
  team_email: "test.team@nhs.net"
  description: "Docs without scaffold test"
  python_version_number: "3.11"
  git_hosting_platform: "gitlab"
  repository_url: "https://gitlab.com/nhsengland/docs_no_scaffold_project"
  environment_manager: "uv"
  testing_framework: "pytest"
  linting_and_formatting: "ruff"
  open_source_license: "GPL-3.0"
  docs: "mkdocs"
  include_code_scaffold: "No"

python_312:
  config_description: "Python 3.12 version test"
  project_name: "python312_project"
  author_name: "Test Author"
  author_email: "test@example.com"
  organization_name: "NHS England"
  team_name: "Test Team"
  team_email: "test.team@nhs.net"
  description: "Python 3.12 test"
  python_version_number: "3.12"
  git_hosting_platform: "github"
  repository_url: "https://github.com/nhsengland/python312_project"
  environment_manager: "poetry"
  testing_framework: "pytest"
  linting_and_formatting: "ruff"
  open_source_license: "MIT"
  docs: "none"
  include_code_scaffold: "Yes"

virtualenv_pyproject:
  config_description: "Virtualenv with pyproject.toml"
  project_name: "virtualenv_pyproject"
  author_name: "Test Author"
  author_email: "test@example.com"
  organization_name: "NHS England"
  team_name: "Test Team"
  team_email: "test.team@nhs.net"
  description: "Virtualenv with pyproject.toml"
  python_version_number: "3.11"
  git_hosting_platform: "github"
  repository_url: "https://github.com/nhsengland/virtualenv_pyproject"
  environment_manager: "virtualenv"
  testing_framework: "pytest"
  linting_and_formatting: "flake8+black+isort"
  open_source_license: "No license file"
  docs: "none"
  include_code_scaffold: "No"
